name: Despliegue a EC2
on:
  push:
    branches: [ "main" ] # O "master", revisa cual es tu rama principal

jobs:
  deploy:
    runs-on: self-hosted # <--- ESTO ES LA CLAVE. Usa tu servidor, no el de GitHub.
    steps:
      - name: Descargar cÃ³digo
        uses: actions/checkout@v3
      
      - name: Instalar dependencias
        run: npm install
        
      - name: Mostrar archivos (Debug)
        run: ls -R
